### ISSUE TITLE
activate() function on Crypto.com Defi wallet doesn't work on IOS devices.

### ISSUE THREAD

**Issue by phenixfinance** [crypto-com/deficonnect-monorepo#9] opened 2022-04-26 10:28 UTC
Been running into some trouble and I'm not sure if it's a support issue or an issue with the functions in my code. The connection seems to execute perfectly on Android devices but nothing happens on IOS. Here is my implementation:

```
            const connector = new DeFiWeb3Connector({
                supportedChainIds: [Config.rpcNetwork_mainnet.chainId],
                rpc: {
                    [Config.rpcNetwork_mainnet.chainId]: Config.rpcNetwork_mainnet.rpcUrl
                },
                pollingInterval: 15000
            });

            connector.activate().then(() => {
                connector.getProvider().then((_provider) => {
                    provider = _provider;
                    web3Provider = new ethers.providers.Web3Provider(provider);

                    if (!(parseInt(provider.chainId) === Config.rpcNetwork_mainnet.chainId)) {
                        window.alert('Switch your Wallet to blockchain network ' + Config.rpcNetwork_mainnet.chainName);
                    }

                    setWallet(web3Provider.getSigner());
                    setAddress(web3Provider.provider.accounts[0]);
                });
            });
```

Anything here that is obvious?

Thanks in advance.

**Comment by nwhite89** [comment] 2022-06-07 15:20
@einaralex I'm not sure that will be the issue Cronos devs on their discord said this was intended behaviour and that for the in built browser to the DeFi wallet to be used a dApp has to be manually approved by them. Strictly speaking this is really bizzare that it's not a pop up of some kind that the user approves it themselves like wallet connect but just as a heads up.

**Comment by andy-bin-cn** [comment] 2022-06-10 10:06
Hi @phenixfinance  in app browser only support dapps which in the dapp list currently.
and you can find the dapp listing form here https://cronos.org/docs/resources/web-extension-integration.html#introduction

**Comment by artemisone-org** [comment] 2022-06-17 18:23
To anyone stuck @einaralex 
@phenixfinance 

I've been revamping our codebase to the latest deficonnector and have found myself frustrated because it simply doesn't work (tm). I have had to fallback to `deficonnect@1.1.0-alpha.37` as it no longer even bothers to confirm your connection with the site. 

Reworked and analyzed the code. This is my functional code

```  "custom-cdc": {
    display: {
      logo: "/img/crypto.com.png",
      name: "Crypto.com",
      description: "Crypto.com DeFi Wallet | Extension",
    },
    options: {
      supportedChainIds: [25, 338],
      rpc: {
        25: "https://rpc.artemisone.org/cronos/", // the (best) Cronos RPC
        338: "https://cronos-testnet-3.crypto.org:8545/",
        31337: "http://127.0.0.1:8545/",
      },
      pollingInterval: 15000,
    },
    package: DeFiConnector,
    connector: async (packageConnector: any, options: any) => {
      let ga = GA_WALLET_EVENT;
      ga.action = "Crypto.com DeFi Wallet";
      ReactGA.event(ga);
      const provider = new packageConnector({
        name: "Crypto.com Cronos",
        supprtedChainTypes: ["eth"],
        supportedChainTypes: ["eth"],
        eth: options,
        cosmos: null,
      });

      await provider.activate();
      return provider.getProvider();
    },
  },```

iOS

![image](https://user-images.githubusercontent.com/95833113/174355910-977208b0-c71e-44b5-932c-570c35c8f0c1.png)



To Cronos developers. we can't use the latest updates. We don't know why. I don't know why we are stuck with the 1.1* versions. None of the new updates seem to work.

**Comment by andy-bin-cn** [comment] 2022-10-31 01:40
seems have fixed on new mobile app version. will close this issue.

**Closed by andy-bin-cn** 2022-10-31 01:40 UTC
